//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class characterdata
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string pic { get; set; }
        public string bio { get; set; }
        public string plot { get; set; }
        public Nullable<int> typeid { get; set; }
    }
}
