//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANmanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class manhwadata
    {
        public int Id { get; set; }
        public Nullable<int> novelid { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string ustatus { get; set; }
        public Nullable<int> noc { get; set; }
        public Nullable<int> unoc { get; set; }
        public string pic { get; set; }
        public string genre { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> releasedate { get; set; }
        public string weblink { get; set; }
        public string desc { get; set; }
        public string aname { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> urating { get; set; }
    }
}
